### ISSUE TITLE
[Question] Update to android 34 or 35

### ISSUE THREAD

**Issue by doiya46** [callstack/super-app-showcase#94] opened 2024-07-06 06:10 UTC
Hi, I have an question about update android version

```
From August 31, 2024, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

How to fix
Your highest non-compliant target API level is Android 13 (API level 33).

To ensure that you can continue to make updates to your app you must:

Update your app to target Android 14 (API level 34) or higher.
Publish a new version of your app to production. Before you do this, you can test your app using internal, closed, or open testing.
```

![image](https://github.com/callstack/super-app-showcase/assets/61301244/35e59ec4-42ea-441a-b455-ee3536b245e9)

**Comment by doiya46** [comment] 2024-07-08 10:49
@jbroma can you help me to resolve this issue.

**Comment by jbroma** [comment] 2024-07-08 13:34
@doiya46 I can't really see how this is connected to `super-app-showcase` and I'll close this issue for now

My take on the issue is that all you need to do become compliant is to to upgrade `react-native` within your own app - or just bump the target API level within the host app.

**Closed by jbroma** 2024-07-08 13:34 UTC
Labels: question
